#!/usr/bin/perl
##
## Programmer:    Craig Stuart Sapp <craig@ccrma.stanford.edu>
## Creation Date: Wed 07 Jul 2021 12:45:24 PM PDT
## Last Modified: Wed 07 Jul 2021 12:45:29 PM PDT
## Filename:      /var/www/cgi-bin/humdrum2musicxml.pl
## Syntax:        Perl 5; CGI
## $Smake:        cp -f %f /var/www/cgi-bin/%b
## vim:           ts=3
##
## Description:   Convert Humdrum data into MusicXML files.
##                Backend for https://musicxml.humdrum.org
##                and https://verovio.humdrum.org
##

use strict;
use CGI;
use Digest::MD5 qw(md5 md5_hex md5_base64);
use IPC::Open2; 

my $cgi_form = new CGI;

# Configuration variables:
my $basedir      = "/project/humdrum2musicxml";
my $cachedir     = "$basedir/cache";
my $maxsize      = 1000000;  # largest file size to allow (1MB)

# Command-line tools:
my $humdrum2musicxml = "/usr/bin/python3 -m converter21 -f humdrum -t musicxml - -";
my $cleanMusicxml    = "$basedir/bin/cleanMusicxml";

##########################################################################
# Main Input Extraction & Processing Flow
##########################################################################

my $File = $cgi_form->param('inputdata');
my $inputdata = "";

if (defined $File) {
	# Safe check to see if Apache passed an open stream/filehandle reference
	if (ref($File) || fileno($File)) {
		my $Buffer = "";
		while (read($File, $Buffer, 1024)) {
			$inputdata .= $Buffer;
		}
	} else {
		# If it's a plain text string (from LWP/curl), assign it directly
		$inputdata = $File;
	}
}

# Validate that the score payload isn't empty
if ($inputdata =~ /^\s*$/) {
	errorMessage("Error: no input score");
} else {
	convertToMusicxml($inputdata);
}

exit(0);

##########################################################################
# Core Conversion Logic
##########################################################################

sub convertToMusicxml {
	my ($inputdata) = @_;

	# Enforce file size checks based on the HTTP transaction context
	if (defined $ENV{'CONTENT_LENGTH'} && $ENV{'CONTENT_LENGTH'} > $maxsize) {
		errorMessage("Input data is too large");
		return;
	}

	# Define the system shell tool chain
	my $command = "$humdrum2musicxml | $cleanMusicxml";
#	my $command = "$humdrum2musicxml ";
	print STDERR "COMMAND RUNNING: $command\n";

	my $outputdata = "";

	# Open bidirectional filehandles ($reader reads output, $writer sends input)
	eval {
		my ($reader, $writer);
		my $pid = open2($reader, $writer, $command);

		# 1. Pump the Humdrum raw text into the commands standard input
		print $writer $inputdata;
		close($writer); # Close writer so the shell knows input is finished

		# 2. Extract the converted MusicXML text back from the stdout stream
		while (my $line = <$reader>) {
			$outputdata .= $line;
		}
		close($reader);

		# 3. Clean up the system process record
		waitpid($pid, 0);
	};

	# Trap execution exceptions (e.g. if converter21 or python environment is missing)
	if ($@) {
		errorMessage("Backend pipeline execution failed: $@");
		exit(0);
	}

	print STDERR "OUTPUT SIZE: " . length($outputdata) . " bytes\n";

	# Verify if the returned data contains a valid XML declaration header
	if ($outputdata =~ /^<\?xml/ || $outputdata =~ /^<\?mxl/) {
		print "Content-Type: text/x-musicxml\n\n";
		print $outputdata;
	} else {
		# Return execution errors generated by Python straight to the client
		errorMessage($outputdata || "Error: Conversion pipeline returned an empty response.");
	}
}

##############################
##
## errorMessage --
##

sub errorMessage {
	my ($message) = @_;
	print "Content-Type: text/plain\n\n";
	print "$message\n";
}

##############################
##
## printParameters --
##

sub printParameters {
	my $output = "";
	my $name;
	my $value;
	foreach my $name ($cgi_form->param) {
		foreach my $value ($cgi_form->param($name)) {
			$output .= "$name ==\t$value\n";
		}
	}

	print "Content-Type: text/plain\n\n";
	print "CGI parameters:\n";
	print "$output\n";
}

##############################
##
## getDate --
##

sub getDate {
	my $cyear;   # current year
	my $cmonth;  # current month
	my $cday;    # current day
	my $chour;   # current hour
	my $cmin;    # current minute
	my $csec;    # current second
	my $weekday; # current weekday
	my $dayofyear;       # current day of year
	my $isdst;   # current timezone

	($csec, $cmin, $chour, $cday, $cmonth, $cyear,
			$weekday, $dayofyear, $isdst) = localtime(time);

	$cmonth += 1;     # fix month so that it is in the range [1-12]
	$cyear += 1900;   # fix year so that it is actual year.

	if ($cmonth < 10) { $cmonth = "0" . int($cmonth); }
	if ($cday < 10)   { $cday   = "0" . int($cday); }
	if ($chour < 10)  { $chour  = "0" . int($chour); }
	if ($cmin < 10)   { $cmin   = "0" . int($cmin); }
	if ($csec < 10)   { $csec   = "0" . int($csec); }

	return ($cyear, $cmonth, $cday, $chour, $cmin, $csec);
}