## 
## vim: ts=3:nowrap
##
## This configuration allows for both HTTPS and HTTP
## The HTTP connection is needed for the command-line
## Humdrum Extras tools.
##

<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerName   data.musicxml.humdrum.org
	DocumentRoot /var/www/websites/humdrum2musicxml
	CustomLog    logs/humdrum2musicxml.log combined
	ErrorLog     logs/humdrum2musicxml-error.log
	ServerAdmin  craig@ccrma.stanford.edu
	ScriptAlias  /cgi-bin/ "/var/www/cgi-bin/"
	ScriptAlias  / "/var/www/cgi-bin/humdrum2musicxml"
	<Directory /var/www/websites/humdrum2musicxml>
		AllowOverride All
		Options Indexes FollowSymLinks
		IndexOptions FancyIndexing ScanHTMLTitles IconHeight=10 IconWidth=11 SuppressDescription NameWidth=45 
		Order allow,deny
		Allow from all
	</Directory>
	<Directory "/var/www/cgi-bin">
		Header set Access-Control-Allow-Origin "*"
		AllowOverride All
		Options None
		Order allow,deny
		Allow from all
	</Directory>
	SSLCertificateFile /etc/letsencrypt/live/data.musicxml.humdrum.org/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/data.musicxml.humdrum.org/privkey.pem
	Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>

<VirtualHost *:80>
	ServerName   data.musicxml.humdrum.org
	DocumentRoot /var/www/websites/humdrum2musicxml
	CustomLog    logs/humdrum2musicxml.log combined
	ErrorLog     logs/humdrum2musicxml-error.log
	ServerAdmin  craig@ccrma.stanford.edu
	ScriptAlias  /cgi-bin/ "/var/www/cgi-bin/"
	ScriptAlias  / "/var/www/cgi-bin/humdrum2musicxml"
	<Directory /var/www/websites/humdrum2musicxml>
		AllowOverride All
		Options Indexes FollowSymLinks
		IndexOptions FancyIndexing ScanHTMLTitles IconHeight=10 IconWidth=11 SuppressDescription NameWidth=45 
		Order allow,deny
		Allow from all
	</Directory>
	<Directory "/var/www/cgi-bin">
		Header set Access-Control-Allow-Origin "*"
		AllowOverride All
		Options None
		Order allow,deny
		Allow from all
	</Directory>
</VirtualHost>


